import minha_biblioteca.calculos as calc

print("Soma:")
print(calc.somar(5, 3))
print("Subtração:")
print(calc.subtrair(5, 3))
print("Multiplicação:")
print(calc.multiplicar(5, 3))
print("Divisão:")
print(calc.dividir(5, 3))
print("Potência:")
print(calc.potencia(5, 3))
print("Raiz Quadrada:")
print(calc.raiz_quadrada(25))
print("Fatorial:")
print(calc.fatorial(5))
print("Média:")
print(calc.media([1, 2, 3, 4, 5]))
print("Máximo:")
print(calc.maximo([1, 2, 3, 4, 5]))
print("Mínimo:")
print(calc.minimo([1, 2, 3, 4, 5]))
